/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import models.Status;
import models.User;
import models.Worker;
import services.FileManager;

/**
 *
 * @author Slobodan
 */
public class WorkerView extends javax.swing.JFrame {
    private Worker currentWorker;

    /**
     * Creates new form WorkerView
     */
    public WorkerView() {
        initComponents();
    }
    
    public WorkerView(Worker w) {
        initComponents();
        
        this.currentWorker = w;
        
        if(w.getStatusId() == 1 || w.getStatusId() == 2) {
            PromoteBtn.setVisible(false);
        }
        
        if(w.getStatusId() == 2) {
            PromoteBtn.setVisible(false);
            FireWorkerBtn.setVisible(false);
        }
       
        loadTable();
        loadStatusesTable();
    }
    
    public void loadTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) Table.getModel();
        Vector<Object> row = new Vector<>();
        row.add(this.currentWorker.getId());
        row.add(this.currentWorker.getFirstName());
        row.add(this.currentWorker.getLastName());
        defaultTableModel.addRow(row);
        WorkerName.setText(this.currentWorker.getFirstName());
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        Table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        Table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        Table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        TableCellRenderer rendererFromHeader = Table.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        Table.setModel(defaultTableModel);
    }
    
    public void loadStatusesTable() {
        FileManager m = new FileManager();
        java.util.List<Status> statuses = m.loadWorkerStatuses(this.currentWorker.getId());
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) StatusesTable.getModel();
        int rowCount = 0;
        
        for(Status s : statuses) {
            Vector<Object> row = new Vector<>();
           
            row.add(s.getDate());
            row.add(s.getTime());
            row.add(s.getId());
            defaultTableModel.addRow(row);
            rowCount ++;
        }
            
        defaultTableModel.setRowCount(rowCount);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        StatusesTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        StatusesTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        StatusesTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
 
        TableCellRenderer rendererFromHeader = StatusesTable.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        StatusesTable.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorkerName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        FireWorkerBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        PromoteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatusesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WorkerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Surname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        FireWorkerBtn.setText("Fire Worker");
        FireWorkerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FireWorkerBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        PromoteBtn.setText("Promote");
        PromoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoteBtnActionPerformed(evt);
            }
        });

        StatusesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "StatusId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(StatusesTable);

        jLabel1.setText("Worker Statuses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(WorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BackBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FireWorkerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(95, 95, 95)
                                    .addComponent(PromoteBtn))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(WorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FireWorkerBtn)
                    .addComponent(BackBtn)
                    .addComponent(PromoteBtn))
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FireWorkerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FireWorkerBtnActionPerformed
        // TODO add your handling code here:
      Worker w = this.currentWorker;
      JOptionPane j = new JOptionPane();
      
      if(j.showConfirmDialog(this, "Are you sure you want to fire worker " + w.getFirstName() + " " + w.getLastName() + " " + "?") == j.YES_OPTION){
          w.setStatusId(2);
          w.setWorkEnd(new Date());
          FileManager manager = new FileManager();
          
          manager.updateWorker(w);
          loadStatusesTable();
      };
    }//GEN-LAST:event_FireWorkerBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        WorkersList l = new WorkersList();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void PromoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoteBtnActionPerformed
        // TODO add your handling code here:
        Worker w = this.currentWorker;
        JOptionPane j = new JOptionPane();
        
        if(j.showConfirmDialog(this, "Are you sure you want to promote worker " + w.getFirstName() + " " + w.getLastName() + " " + "?") == j.YES_OPTION){
            w.setStatusId(1);
            
            FileManager manager = new FileManager();
            User u = new User(w.getFirstName(), w.getLastName(), w.getUsername(), "Manager", w.getPassword(), w.getId());
            
            manager.writeNewUser(u);
            manager.updateWorker(w);
            loadStatusesTable();
        }
    }//GEN-LAST:event_PromoteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton FireWorkerBtn;
    private javax.swing.JButton PromoteBtn;
    private javax.swing.JTable StatusesTable;
    private javax.swing.JTable Table;
    private javax.swing.JLabel WorkerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
